### ISSUE TITLE
How to stop it Bro!

### ISSUE THREAD

**Issue by T4P4N** [UltimateHackers/Shiva#2]
crtl c is not working

**Comment by UltimateHackers** [comment]
There's not stopping mechanism implemented in it at present.
Closing the terminal will help :v

**Comment by Souhardya** [comment]
F

**Comment by sachincool** [comment]
U

**Comment by Souhardya** [comment]
No u

**Comment by thehappydinoa** [comment]
@UltimateHackers do you want me to implement a hard stop? and make a requirements.txt?
